# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f4bba09fb111a89b221d384f22584884d72d522e034603e7a835f7887e1dc5fab9abf36e202d77c0ef9fc29c4a1e561aacd3e4ff8aa583bf1262e311ae6d80e

test:
  secret_key_base: 2179a3029e42eb4d8f4e503735ce469cca6163cc6277af7fa5eb20043c86c3f73cf11a2ed415434d689edf099c14ef8549e36896289d6a9c86d7d702327d911a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
